### PR TITLE
some lintings

### PR DESCRIPTION
**Pull request by fperrad**
this set of patches solves problems found with a lint tool.

I try to have a commit per kind of problem.

### CODE REVIEW

**Comment by fperrad** [comment]
rebased and fixed

**Comment by mkj** [comment]
Apart from those 3 commits it looks good, ready to merge.

**Comment by fperrad** [comment]
These 3 commits concern the coding style of the project, so mainly about  your personal taste.

The only critical commit is bbae9346088947450bcb712bc9d2f1d252848b28 , I think that is a bug.

**Comment by mkj** [comment]
I've cherry picked all of these apart from the 3 - thank you. 
bbae934 is certainly a bug - luckily I don't think it has an impact since the socket will be presented again the next time select() is called. 

If only I could use c99 for-loop variable declarations...

**Pull request closed without merging**
