### PR TITLE
dbclient: support -o StrictHostKeyChecking

### LINKED ISSUE #226: Support OpenSSH's StrictHostKeyChecking option with accept-new flag
From the [ssh_config man page](https://man.openbsd.org/ssh_config):

> If this flag is set to **accept-new** then ssh will automatically add new host keys to the user's known_hosts file, but will not permit connections to hosts with changed host keys.

This is useful for automated management of (new) hosts. This is also more secure compared to using `-y` since it stores the host key in known_hosts, therefore not requiring `-y` in future sessions when connecting to the same host.

Example usage:
```
dbclient -oStrictHostKeyChecking=accept-new user@somenewhost "echo yes"
```

Alternatively:
Please include functionality from `ssh-keyscan` to allow printing host keys of (new) hosts.

Example usage (where `-S` is a new switch and `-t ed25519` limits the output to the corresponding key type):
```
dbclient -S -t ed25519 somenewhost
```
Example output:
```
somenewhost ssh-ed25519 ABCDE(...)
```

For compactness over functionality, the requested functionality could be limited to just `-S`, to have the output of all offered keys filtered elsewhere.

### PR DESCRIPTION
**Pull request by stokito**
Fixes #226

### CODE REVIEW

**Comment by stokito** [comment]
I added other options that already have a flag. This will make interoperability with OpenSSH better because -K -J flags have a different meaning. So with the options we can help to write scripts that will work similarly.
Unfortunately this also makes code bigger but i hope that not so much. We can make a condition to compile only those options that doesn't have a flag or the flag meaning differs.
Still I believe that if someone have a place for Dropbear then they are probably ready to have some extra kilobytes.

**Comment by stokito** [comment]
@Zepmann please test the `StrictHostKeyChecking` and `BatchMode` that you asked for in #224

**Comment by Zepmann** [comment]
Tested.

`-oBatchMode=yes` seems to work fine. 👍

The behavior of `-oStrictHostKeyChecking=accept-new` is not what is expected. With `-oStrictHostKeyChecking=accept-new`, the SSH client does not write the server's public key to `known_hosts`. If a `known_hosts` file does not exist, it will be created with 0 bytes of content. If known_hosts does exist, its content is not changed and the modification date is not updated, hinting that nothing is written/changed.

**Comment by stokito** [comment]
Right, so the dbclient should also store the hostkey to known_hosts without confirming.
I may try to fix that but in nearest time may not have a time for this.

**Comment by stokito** [comment]
@Zepmann I fixed the bug in a separate https://github.com/mkj/dropbear/pull/271

I don't know if Matt will accept the PR but at least for that bug fix should be easier to pass review.
If you can, please merge that branch and re-test.
Thank you

**Comment by mkj** [comment]
Thanks, this has been requested a bit. I still need to review the code.

One thing I notice, `BatchMode` disables password auth unconditionally. But it seems it should be allowed if using `DROPBEAR_PASSWORD` env var, or `SSH_ASKPASS`? (I can make the changes on top of this PR).

**Comment by stokito** [comment]
will add a fix in a minute

**Comment by Zepmann** [comment]
`BatchMode` should prevent the need for any user interaction. All other program behavior should be as usual from an admin expectation perspective.

Just my 2 cents. Thanks for the work so far, @stokito and @mkj.

**Comment by stokito** [comment]
I moved the batch mode cheking before the `getpass()` call.

**Comment by stokito** [comment]
Updated man page with new options

**Comment by HansH111** [comment]
For multihop support you need to change  multihop_passthrough_args()  in cli-runopts.c and pass the -o values.

**Comment by stokito** [comment]
The options shouldn't be applied to jump servers. Or maybe the dropbear supports this? If you know how to make it please send a PR once this become merged.

**Comment by HansH111** [comment]
Maybe not, but I see -y -y being passed when using multihop in function 
multihop_passthrough_args() in cli-runopts.c

**Comment by HansH111** [comment]
I just checked and removed the -y -y in that function and when I do a multihop now, it asks for confirmation because the hostkey is not in the trusted host file.

**Comment by stokito** [comment]
I tested how the PasswordAuth and BatchMode works with keyboard interactive auth. No issues with this.

The BatchMode=yes won't stuck in interactive auth but it will try it and fail only when the interactive asks for a user input. This is even better behavior that OpenSSH client have.
For example you can ssh to srv.us (free ssh tunnels provider) and it will ask for interactive mode but authorize immediately without asking.

When the PasswordAuth=no it will stuck in the interactive mode and wait for a user unput.

**Comment by HansH111** [comment]
Added a pull request for -o BatchMode=yes and also passed it when multihop was selected.
I am not very experienced in git....  I have no idea how to put it in this pull request .

**Comment by stokito** [comment]
@HansH111 make an archive and send to me at stokito@gmail.com. You can't add commits to another one's PR

**Comment by mkj** [comment]
I've pushed a few changes on top of this, and added in PR #281 from @HansH111 . 

`stricthostkeychecking=yes` is changed a bit, previously it was asking whether to add.

**Comment by stokito** [comment]
Thank you, I'll retest today.

**Pull request merged**
