### PR TITLE
Prefer stronger algorithms in algorithm negotiation.

### PR DESCRIPTION
**Pull request by fedor-brunner**
Prefer diffie-hellman-group14-sha1 (2048 bit) over
 diffie-hellman-group1-sha1 (1024 bit).

Due to meet-in-the-middle attacks the effective key length of
three key 3DES is 112 bits. AES is stronger and faster then 3DES.

Prefer to delay the start of compression until after authentication
has completed. This avoids exposing compression code to attacks
from unauthenticated users.

### CODE REVIEW

**Comment by mkj** [comment]
(CCing the dropbear list - hopefully crossposting isn't too awkward)

I'll merge this pull request, though if anyone has comments
please let me know. Comments inline below.

Matt

On Thu, Jan 08, 2015 at 04:46:48AM -0800, fedor-brunner wrote:

>   https://github.com/mkj/dropbear/pull/9
> 
> -- Commit Summary --
> 
>   * Prefer stronger algorithms in algorithm negotiation.
> 
> -- File Changes --
> 
>     M common-algo.c (16)

> Prefer diffie-hellman-group14-sha1 (2048 bit) over
>  diffie-hellman-group1-sha1 (1024 bit).

This is probably OK. group14 is quite a bit slower for slow
machines (2x?). I don't think that's a big problem though -
the algorithm preference order only applies to Dropbear as a
client. In that case most servers seem to support ecdh
methods which are fast - they're the first preference
(curve25519 and the nist methods). 

> [prefer aes256 over 3des]
> Due to meet-in-the-middle attacks the effective key length of
> three key 3DES is 112 bits. AES is stronger and faster then 3DES.

This makes sense. 

> Prefer to delay the start of compression until after authentication
> has completed. This avoids exposing compression code to attacks
> from unauthenticated users.

I was thinking of doing this recently myself. At the time I
added delayed compression some widespread clients (PuTTY I
think?) didn't suppprt it, but I think that's OK now.

**Comment by fedor-brunner** [comment]
On 09.01.2015 16:00, Matt Johnston wrote:
> (CCing the dropbear list - hopefully crossposting isn't too awkward)
> 
> I'll merge this pull request, though if anyone has comments
> please let me know. Comments inline below.
> 
> Matt
> 
> On Thu, Jan 08, 2015 at 04:46:48AM -0800, fedor-brunner wrote:
> 
>>   https://github.com/mkj/dropbear/pull/9
>>
>> -- Commit Summary --
>>
>>   * Prefer stronger algorithms in algorithm negotiation.
>>
>> -- File Changes --
>>
>>     M common-algo.c (16)
> 
>> Prefer diffie-hellman-group14-sha1 (2048 bit) over
>>  diffie-hellman-group1-sha1 (1024 bit).
> 
> This is probably OK. group14 is quite a bit slower for slow
> machines (2x?). I don't think that's a big problem though -
> the algorithm preference order only applies to Dropbear as a
> client. In that case most servers seem to support ecdh
> methods which are fast - they're the first preference
> (curve25519 and the nist methods). 

According to "Algorithms, key size and parameters report 2014" the
1024-bit Diffie-Hellman is recommended only for legacy applications and
should be replaced for future system use.

https://www.enisa.europa.eu/activities/identity-and-trust/library/deliverables/algorithms-key-size-and-parameters-report-2014

The cryptographic community reached consensus a decade ago that a
1024-bit RSA key can be broken in a year by an attack machine costing
signicantly less than 10^9 dollars.

http://cr.yp.to/factorization/batchnfs-20141109.pdf

**Comment by mkj** [comment]
Merged via mercurial, thanks. 4122cac66b139492d5b7fa6a1b8afcb1bfc529f7

**Comment by kingarley** [comment]
shouldn't
```
#if DROPBEAR_3DES
	{"3des-ctr", 0, &dropbear_3des, 1, &dropbear_mode_ctr},
#endif
```
be under
```
#if DROPBEAR_ENABLE_CTR_MODE
```
instead of being under
```
#if DROPBEAR_ENABLE_CBC_MODE
```

**Pull request closed without merging**
