### PR TITLE
scp: add option to automatically accept signature

### PR DESCRIPTION
**Pull request by teknoraver**
Add an `-y` option which automatically accepts the host key without checking as we did with ssh in commit cd0a08896c83ab20f7cc04e755ce38b1525d47a3

### CODE REVIEW

**Comment by Ansuel** [comment]
@mkj sorry for the tag. Any problem with this simple patch?

**Comment by mkj** [comment]
I wonder if it would be better to have `-o StrictHostKeyChecking=off` rather than adding another extra flag?

**Comment by teknoraver** [comment]
That's to be coherent with `ssh`, which already supports the -y flag

**Comment by mkj** [comment]
I'm reluctant to let `scp` diverge from the flags in upstream OpenSSH - I don't really want to maintain it myself (even OpenSSH have mostly given up on it).

Generally I think the argument lists of `dropbear` and `dbclient` are getting unwieldy, so options that aren't usually typed by hand should go under `-o` instead. Of course `dropbear` itself doesn't have `-o` support yet, but one day it will.

**Comment by stokito** [comment]
Related to #41 that adds -o and  #269 that adds to the dbclient `-o StrictHostKeyChecking`

**Comment by mkj** [comment]
`scp -o stricthostkeychecking` should work since #269

**Pull request closed without merging**
