### PR TITLE
configure.ac: add AC_USE_SYSTEM_EXTENSIONS

### PR DESCRIPTION
**Pull request by ffontaine**
Build fails on uclibc since version DROPBEAR_2020.79 and https://github.com/mkj/dropbear/commit/89e98a2f8382bcaab0e7ba04cb4050c9d62898a4:

```
/home/buildroot/autobuild/instance-2/output-1/host/bin/m68k-linux-gcc -c -DLOCALOPTIONS_H_EXISTS -I. -I. -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -O2 -g2  -fno-dwarf2-cfi-asm  -Wl,-elf2flt -static -Wno-pointer-sign -fno-strict-overflow -DDROPBEAR_SERVER -DPROGRESS_METER -DDBMULTI_dropbear -DDBMULTI_dropbearkey -DDBMULTI_dropbearconvert -DDBMULTI_scp -DDROPBEAR_MULTI -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 dh_groups.c -o dh_groups.o
dbrandom.c: In function 'process_getrandom':
dbrandom.c:174:8: warning: implicit declaration of function 'getrandom'; did you mean 'genrandom'? [-Wimplicit-function-declaration]
  ret = getrandom(buf, sizeof(buf), GRND_NONBLOCK);
        ^~~~~~~~~
        genrandom
/home/buildroot/autobuild/instance-2/output-1/host/bin/m68k-linux-gcc -c -DLOCALOPTIONS_H_EXISTS -I. -I. -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -O2 -g2  -fno-dwarf2-cfi-asm  -Wl,-elf2flt -static -Wno-pointer-sign -fno-strict-overflow -DDROPBEAR_SERVER -DPROGRESS_METER -DDBMULTI_dropbear -DDBMULTI_dropbearkey -DDBMULTI_dropbearconvert -DDBMULTI_scp -DDROPBEAR_MULTI -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 dropbearconvert.c -o dropbearconvert.o
dbrandom.c:174:36: error: 'GRND_NONBLOCK' undeclared (first use in this function); did you mean 'SOCK_NONBLOCK'?
  ret = getrandom(buf, sizeof(buf), GRND_NONBLOCK);
                                    ^~~~~~~~~~~~~
                                    SOCK_NONBLOCK
```

To fix this build failure, add AC_USE_SYSTEM_EXTENSIONS as getrandom is
only defined if _GNU_SOURCE is set on uclibc

Fixes:
 - http://autobuild.buildroot.org/results/d6d783da2fb834ce21475ff54f82c07873246826

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by mkj** [comment]
I've fixed this explicitly setting _GNU_SOURCE in https://github.com/mkj/dropbear/commit/3f5c106a880a02b21739f2022746e6aa7672474c

Not sure why uclibc needs _GNU_SOURCE when glibc doesn't.

Thanks,
Matt

**Comment by ffontaine** [comment]
Setting _GNU_SOURCE in the HAVE_SYS_RANDOM_H block does not fix the build failure.

I assume that _GNU_SOURCE is defined too late and that some system header pulls in getrandom before _GNU_SOURCE is defined. I can try to investigate but I was thinking that  AC_USE_SYSTEM_EXTENSIONS would be cleaner (especially because this is not the only functions that need _GNU_SOURCE).

**Comment by mkj** [comment]
Ah right. AC_USE_SYSTEM_EXTENSIONS will require bumping the autoconf version requirement, I've pushed https://github.com/mkj/dropbear/commit/a7a67585cbc3fe5df85c641618b347a51a943356 which should put _GNU_SOURCE earlier.

**Comment by ffontaine** [comment]
Thanks this time, it is fixed :+1:

**Pull request closed without merging**
