### PR TITLE
improve: README compatible with Github markdown

### LINKED ISSUE #163: Use github compatible markdown for README
The current README file is not formatted for GitHub. Change the formatting to markdown with the necessary changes to formatting.

### PR DESCRIPTION
**Pull request by bevsxyz**
Fixes #163

### CODE REVIEW

**Comment by bevsxyz** [comment]
The readme is more visually appealing now. Check it out at https://github.com/bevsxyz/dropbear#readme

**Comment by bevsxyz** [comment]
I have added the following version badge that gets its version from the latest tag data provided by Github. The data in JSON format is queried with https://shields.io/ to generate the badge, which is nothing but an SVG image. The badge version updation will be independent of the README.md source file.

[Version](https://github.com/mkj/dropbear/releases/latest)

**Comment by stokito** [comment]
Just noticed your PR after making mine https://github.com/mkj/dropbear/pull/266
maybe you can review it

**Comment by mkj** [comment]
Sorry already merged #266

**Pull request closed without merging**
